# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\x12OneHealth.analysis\"\xe4\x01\n\x0f\x41nalysisRequest\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_unix_ts\x18\x02 \x01(\x04\x12\x12\n\nto_unix_ts\x18\x03 \x01(\x04\x12\x12\n\ndata_types\x18\x04 \x03(\t\x12\x12\n\nsensor_ids\x18\x05 \x03(\r\x12\x41\n\x07options\x18\x06 \x03(\x0b\x32\x30.OneHealth.analysis.AnalysisRequest.OptionsEntry\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xf1\x01\n\x0e\x41nalysisResult\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x14\n\x0csummary_text\x18\x02 \x01(\t\x12/\n\x06series\x18\x03 \x03(\x0b\x32\x1f.OneHealth.analysis.SeriesPoint\x12@\n\x07metrics\x18\x04 \x03(\x0b\x32/.OneHealth.analysis.AnalysisResult.MetricsEntry\x12\x18\n\x10produced_unix_ts\x18\x05 \x01(\x04\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"7\n\x0bSeriesPoint\x12\n\n\x02ts\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x01\x12\r\n\x05label\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"\"\n\x11\x41vailableAnalyses\x12\r\n\x05kinds\x18\x01 \x03(\t2\xc4\x01\n\x0f\x41nalysisService\x12V\n\x0bRunAnalysis\x12#.OneHealth.analysis.AnalysisRequest\x1a\".OneHealth.analysis.AnalysisResult\x12Y\n\x15ListAvailableAnalyses\x12\x19.OneHealth.analysis.Empty\x1a%.OneHealth.analysis.AvailableAnalysesB\x1a\xaa\x02\x17OneHealth.Grpc.Analysisb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\027OneHealth.Grpc.Analysis'
  _globals['_ANALYSISREQUEST_OPTIONSENTRY']._loaded_options = None
  _globals['_ANALYSISREQUEST_OPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_ANALYSISRESULT_METRICSENTRY']._loaded_options = None
  _globals['_ANALYSISRESULT_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_ANALYSISREQUEST']._serialized_start=39
  _globals['_ANALYSISREQUEST']._serialized_end=267
  _globals['_ANALYSISREQUEST_OPTIONSENTRY']._serialized_start=221
  _globals['_ANALYSISREQUEST_OPTIONSENTRY']._serialized_end=267
  _globals['_ANALYSISRESULT']._serialized_start=270
  _globals['_ANALYSISRESULT']._serialized_end=511
  _globals['_ANALYSISRESULT_METRICSENTRY']._serialized_start=465
  _globals['_ANALYSISRESULT_METRICSENTRY']._serialized_end=511
  _globals['_SERIESPOINT']._serialized_start=513
  _globals['_SERIESPOINT']._serialized_end=568
  _globals['_EMPTY']._serialized_start=570
  _globals['_EMPTY']._serialized_end=577
  _globals['_AVAILABLEANALYSES']._serialized_start=579
  _globals['_AVAILABLEANALYSES']._serialized_end=613
  _globals['_ANALYSISSERVICE']._serialized_start=616
  _globals['_ANALYSISSERVICE']._serialized_end=812
# @@protoc_insertion_point(module_scope)
