# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import analysis_pb2 as analysis__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalysisServiceStub(object):
    """AnalysisService é invocado pelo Servidor Central para realizar análises
    estatísticas, deteção de padrões e previsões sobre os dados persistidos
    em PostgreSQL. Implementado em Python (pandas / numpy / scikit-learn).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunAnalysis = channel.unary_unary(
                '/onehealth.analysis.AnalysisService/RunAnalysis',
                request_serializer=analysis__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=analysis__pb2.AnalysisResult.FromString,
                _registered_method=True)
        self.ListAvailableAnalyses = channel.unary_unary(
                '/onehealth.analysis.AnalysisService/ListAvailableAnalyses',
                request_serializer=analysis__pb2.Empty.SerializeToString,
                response_deserializer=analysis__pb2.AvailableAnalyses.FromString,
                _registered_method=True)


class AnalysisServiceServicer(object):
    """AnalysisService é invocado pelo Servidor Central para realizar análises
    estatísticas, deteção de padrões e previsões sobre os dados persistidos
    em PostgreSQL. Implementado em Python (pandas / numpy / scikit-learn).
    """

    def RunAnalysis(self, request, context):
        """Executa uma análise paramétrica (intervalo temporal, tipos, sensores,
        zona) e devolve um sumário, série e métricas.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAvailableAnalyses(self, request, context):
        """Devolve os tipos de análise disponíveis (para popular dropdowns na UI).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.RunAnalysis,
                    request_deserializer=analysis__pb2.AnalysisRequest.FromString,
                    response_serializer=analysis__pb2.AnalysisResult.SerializeToString,
            ),
            'ListAvailableAnalyses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvailableAnalyses,
                    request_deserializer=analysis__pb2.Empty.FromString,
                    response_serializer=analysis__pb2.AvailableAnalyses.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onehealth.analysis.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('onehealth.analysis.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService(object):
    """AnalysisService é invocado pelo Servidor Central para realizar análises
    estatísticas, deteção de padrões e previsões sobre os dados persistidos
    em PostgreSQL. Implementado em Python (pandas / numpy / scikit-learn).
    """

    @staticmethod
    def RunAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onehealth.analysis.AnalysisService/RunAnalysis',
            analysis__pb2.AnalysisRequest.SerializeToString,
            analysis__pb2.AnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAvailableAnalyses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onehealth.analysis.AnalysisService/ListAvailableAnalyses',
            analysis__pb2.Empty.SerializeToString,
            analysis__pb2.AvailableAnalyses.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
