// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: preprocessing.proto

package preproc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PreProcessor_Normalize_FullMethodName      = "/onehealth.preproc.PreProcessor/Normalize"
	PreProcessor_NormalizeBatch_FullMethodName = "/onehealth.preproc.PreProcessor/NormalizeBatch"
)

// PreProcessorClient is the client API for PreProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PreProcessor é invocado pelo Gateway antes do encaminhamento para o
// Servidor Central. Garante normalização de unidades, validação de limites
// e descarte de leituras corrompidas / fora de gama.
type PreProcessorClient interface {
	// Normaliza uma única leitura. Para baixa latência / alertas urgentes.
	Normalize(ctx context.Context, in *RawMeasurement, opts ...grpc.CallOption) (*NormalizedMeasurement, error)
	// Normaliza um lote (caso de uso: batch de 10 do Sensor).
	NormalizeBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error)
}

type preProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewPreProcessorClient(cc grpc.ClientConnInterface) PreProcessorClient {
	return &preProcessorClient{cc}
}

func (c *preProcessorClient) Normalize(ctx context.Context, in *RawMeasurement, opts ...grpc.CallOption) (*NormalizedMeasurement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NormalizedMeasurement)
	err := c.cc.Invoke(ctx, PreProcessor_Normalize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preProcessorClient) NormalizeBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, PreProcessor_NormalizeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PreProcessorServer is the server API for PreProcessor service.
// All implementations must embed UnimplementedPreProcessorServer
// for forward compatibility.
//
// PreProcessor é invocado pelo Gateway antes do encaminhamento para o
// Servidor Central. Garante normalização de unidades, validação de limites
// e descarte de leituras corrompidas / fora de gama.
type PreProcessorServer interface {
	// Normaliza uma única leitura. Para baixa latência / alertas urgentes.
	Normalize(context.Context, *RawMeasurement) (*NormalizedMeasurement, error)
	// Normaliza um lote (caso de uso: batch de 10 do Sensor).
	NormalizeBatch(context.Context, *BatchRequest) (*BatchResponse, error)
	mustEmbedUnimplementedPreProcessorServer()
}

// UnimplementedPreProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPreProcessorServer struct{}

func (UnimplementedPreProcessorServer) Normalize(context.Context, *RawMeasurement) (*NormalizedMeasurement, error) {
	return nil, status.Error(codes.Unimplemented, "method Normalize not implemented")
}
func (UnimplementedPreProcessorServer) NormalizeBatch(context.Context, *BatchRequest) (*BatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NormalizeBatch not implemented")
}
func (UnimplementedPreProcessorServer) mustEmbedUnimplementedPreProcessorServer() {}
func (UnimplementedPreProcessorServer) testEmbeddedByValue()                      {}

// UnsafePreProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PreProcessorServer will
// result in compilation errors.
type UnsafePreProcessorServer interface {
	mustEmbedUnimplementedPreProcessorServer()
}

func RegisterPreProcessorServer(s grpc.ServiceRegistrar, srv PreProcessorServer) {
	// If the following call panics, it indicates UnimplementedPreProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PreProcessor_ServiceDesc, srv)
}

func _PreProcessor_Normalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMeasurement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreProcessorServer).Normalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreProcessor_Normalize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreProcessorServer).Normalize(ctx, req.(*RawMeasurement))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreProcessor_NormalizeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreProcessorServer).NormalizeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreProcessor_NormalizeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreProcessorServer).NormalizeBatch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PreProcessor_ServiceDesc is the grpc.ServiceDesc for PreProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PreProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onehealth.preproc.PreProcessor",
	HandlerType: (*PreProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Normalize",
			Handler:    _PreProcessor_Normalize_Handler,
		},
		{
			MethodName: "NormalizeBatch",
			Handler:    _PreProcessor_NormalizeBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "preprocessing.proto",
}
