// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: preprocessing.proto

package preproc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensagem original tal como o Gateway a recebeu via Pub/Sub (Fase 1 do TP2).
type RawMeasurement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      uint32                 `protobuf:"varint,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // "TEMP","HUM","PM25","PM10","RUIDO","LUM"
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	UnixTs        uint64                 `protobuf:"varint,4,opt,name=unix_ts,json=unixTs,proto3" json:"unix_ts,omitempty"`
	Zona          string                 `protobuf:"bytes,5,opt,name=zona,proto3" json:"zona,omitempty"`
	SourceFormat  string                 `protobuf:"bytes,6,opt,name=source_format,json=sourceFormat,proto3" json:"source_format,omitempty"` // "BIN","JSON","XML","CSV" — informativo
	UnitHint      string                 `protobuf:"bytes,7,opt,name=unit_hint,json=unitHint,proto3" json:"unit_hint,omitempty"`             // "C","F","K","ugm3","dB","lx","pct" — opcional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawMeasurement) Reset() {
	*x = RawMeasurement{}
	mi := &file_preprocessing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMeasurement) ProtoMessage() {}

func (x *RawMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_preprocessing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMeasurement.ProtoReflect.Descriptor instead.
func (*RawMeasurement) Descriptor() ([]byte, []int) {
	return file_preprocessing_proto_rawDescGZIP(), []int{0}
}

func (x *RawMeasurement) GetSensorId() uint32 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *RawMeasurement) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *RawMeasurement) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RawMeasurement) GetUnixTs() uint64 {
	if x != nil {
		return x.UnixTs
	}
	return 0
}

func (x *RawMeasurement) GetZona() string {
	if x != nil {
		return x.Zona
	}
	return ""
}

func (x *RawMeasurement) GetSourceFormat() string {
	if x != nil {
		return x.SourceFormat
	}
	return ""
}

func (x *RawMeasurement) GetUnitHint() string {
	if x != nil {
		return x.UnitHint
	}
	return ""
}

type NormalizedMeasurement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      uint32                 `protobuf:"varint,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"` // valor já convertido para unidade canónica
	UnixTs        uint64                 `protobuf:"varint,4,opt,name=unix_ts,json=unixTs,proto3" json:"unix_ts,omitempty"`
	Zona          string                 `protobuf:"bytes,5,opt,name=zona,proto3" json:"zona,omitempty"`
	Dropped       bool                   `protobuf:"varint,6,opt,name=dropped,proto3" json:"dropped,omitempty"`                        // true se a limpeza rejeitou a leitura
	DropReason    string                 `protobuf:"bytes,7,opt,name=drop_reason,json=dropReason,proto3" json:"drop_reason,omitempty"` // motivo legível (e.g. "out_of_bounds:TEMP>70")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedMeasurement) Reset() {
	*x = NormalizedMeasurement{}
	mi := &file_preprocessing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedMeasurement) ProtoMessage() {}

func (x *NormalizedMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_preprocessing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedMeasurement.ProtoReflect.Descriptor instead.
func (*NormalizedMeasurement) Descriptor() ([]byte, []int) {
	return file_preprocessing_proto_rawDescGZIP(), []int{1}
}

func (x *NormalizedMeasurement) GetSensorId() uint32 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *NormalizedMeasurement) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *NormalizedMeasurement) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NormalizedMeasurement) GetUnixTs() uint64 {
	if x != nil {
		return x.UnixTs
	}
	return 0
}

func (x *NormalizedMeasurement) GetZona() string {
	if x != nil {
		return x.Zona
	}
	return ""
}

func (x *NormalizedMeasurement) GetDropped() bool {
	if x != nil {
		return x.Dropped
	}
	return false
}

func (x *NormalizedMeasurement) GetDropReason() string {
	if x != nil {
		return x.DropReason
	}
	return ""
}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RawMeasurement      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_preprocessing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_preprocessing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_preprocessing_proto_rawDescGZIP(), []int{2}
}

func (x *BatchRequest) GetItems() []*RawMeasurement {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*NormalizedMeasurement `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_preprocessing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_preprocessing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_preprocessing_proto_rawDescGZIP(), []int{3}
}

func (x *BatchResponse) GetItems() []*NormalizedMeasurement {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_preprocessing_proto protoreflect.FileDescriptor

const file_preprocessing_proto_rawDesc = "" +
	"\n" +
	"\x13preprocessing.proto\x12\x11onehealth.preproc\"\xcf\x01\n" +
	"\x0eRawMeasurement\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\rR\bsensorId\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x17\n" +
	"\aunix_ts\x18\x04 \x01(\x04R\x06unixTs\x12\x12\n" +
	"\x04zona\x18\x05 \x01(\tR\x04zona\x12#\n" +
	"\rsource_format\x18\x06 \x01(\tR\fsourceFormat\x12\x1b\n" +
	"\tunit_hint\x18\a \x01(\tR\bunitHint\"\xcf\x01\n" +
	"\x15NormalizedMeasurement\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\rR\bsensorId\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x17\n" +
	"\aunix_ts\x18\x04 \x01(\x04R\x06unixTs\x12\x12\n" +
	"\x04zona\x18\x05 \x01(\tR\x04zona\x12\x18\n" +
	"\adropped\x18\x06 \x01(\bR\adropped\x12\x1f\n" +
	"\vdrop_reason\x18\a \x01(\tR\n" +
	"dropReason\"G\n" +
	"\fBatchRequest\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.onehealth.preproc.RawMeasurementR\x05items\"O\n" +
	"\rBatchResponse\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.onehealth.preproc.NormalizedMeasurementR\x05items2\xbd\x01\n" +
	"\fPreProcessor\x12X\n" +
	"\tNormalize\x12!.onehealth.preproc.RawMeasurement\x1a(.onehealth.preproc.NormalizedMeasurement\x12S\n" +
	"\x0eNormalizeBatch\x12\x1f.onehealth.preproc.BatchRequest\x1a .onehealth.preproc.BatchResponseB4Z\x19onehealth/preproc;preproc\xaa\x02\x16OneHealth.Grpc.Preprocb\x06proto3"

var (
	file_preprocessing_proto_rawDescOnce sync.Once
	file_preprocessing_proto_rawDescData []byte
)

func file_preprocessing_proto_rawDescGZIP() []byte {
	file_preprocessing_proto_rawDescOnce.Do(func() {
		file_preprocessing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_preprocessing_proto_rawDesc), len(file_preprocessing_proto_rawDesc)))
	})
	return file_preprocessing_proto_rawDescData
}

var file_preprocessing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_preprocessing_proto_goTypes = []any{
	(*RawMeasurement)(nil),        // 0: onehealth.preproc.RawMeasurement
	(*NormalizedMeasurement)(nil), // 1: onehealth.preproc.NormalizedMeasurement
	(*BatchRequest)(nil),          // 2: onehealth.preproc.BatchRequest
	(*BatchResponse)(nil),         // 3: onehealth.preproc.BatchResponse
}
var file_preprocessing_proto_depIdxs = []int32{
	0, // 0: onehealth.preproc.BatchRequest.items:type_name -> onehealth.preproc.RawMeasurement
	1, // 1: onehealth.preproc.BatchResponse.items:type_name -> onehealth.preproc.NormalizedMeasurement
	0, // 2: onehealth.preproc.PreProcessor.Normalize:input_type -> onehealth.preproc.RawMeasurement
	2, // 3: onehealth.preproc.PreProcessor.NormalizeBatch:input_type -> onehealth.preproc.BatchRequest
	1, // 4: onehealth.preproc.PreProcessor.Normalize:output_type -> onehealth.preproc.NormalizedMeasurement
	3, // 5: onehealth.preproc.PreProcessor.NormalizeBatch:output_type -> onehealth.preproc.BatchResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_preprocessing_proto_init() }
func file_preprocessing_proto_init() {
	if File_preprocessing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_preprocessing_proto_rawDesc), len(file_preprocessing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_preprocessing_proto_goTypes,
		DependencyIndexes: file_preprocessing_proto_depIdxs,
		MessageInfos:      file_preprocessing_proto_msgTypes,
	}.Build()
	File_preprocessing_proto = out.File
	file_preprocessing_proto_goTypes = nil
	file_preprocessing_proto_depIdxs = nil
}
